owner: naphatphong-bwnsc
repo: status

sites:
  - name: BWNSC
    url: https://www.bwnsc.in.th/
  - name: EMAIL@BWNSC
    url: https://email.bwnsc.in.th/
  - name: SOS@BWNSC
    url: https://sos.bwnsc.in.th/
  - name: ระบบเช็กชื่อสภานักเรียนโรงเรียนบุญวัฒนา
    url: https://bwnsc2024.lnw.mn/Check/

status-website:
  cname: status.bwnsc.in.th
  logoUrl: https://www.bwnsc.in.th/logo.png
  name: ระบบสถานะเว็บไซต์ BWNSC
  introTitle: "**ระบบตรวจสอบสถานะเว็บไซต์ BWNSC**"
  introMessage: หน้านี้ใช้แสดงสถานะการออนไลน์ของเว็บไซต์และบริการสำคัญของโรงเรียนบุญวัฒนา
  navbar:
    - title: หน้าหลัก
      href: /
    - title: GitHub
      href: https://github.com/naphatphong-bwnsc/status
